version: '3.8'

services:
  # App for testing the Dockerfile, available when ran with: docker-compose --profile app-demo up
  app-demo:
    build: ./
    profiles:
      - app-demo
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "9000:8080"

  # Development app with livereload using reflex
  app:
    build: ./misc/tools/reflex
    container_name: movies_service
    links:
      - postgres
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    volumes:
      - .:/usr/app

  postgres:
    image: postgres:14.6
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5