name: deploy-production
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Tag to be deployed to production: 0.0.1"
        default: 0.0.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
          ref: refs/tags/v${{ github.event.inputs.version }}

      - uses: arduino/setup-task@v1
        with:
          version: 3.10.0

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Production
        run: task deploy:prd -- v${{ github.event.inputs.version }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
