name: deploy-staging
on:
  workflow_call:
    inputs:
      version:
        required: true
        description: "version to be deployed"
    secrets:
      PAT:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
            ref: refs/tags/v${{ github.event.inputs.version }}

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Staging
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
        run: task deploy:stg
